export type appRoutes =
  | '/'
  | '/classifier'
  | '/classifier/by-rhyme'
  | '/classifier/by-stanza'
  | '/classifier/by-verse'
  | '/upload-poem'
  | '/upload-poem/author-data'
  | '/upload-poem/poem-data'
  | '/upload-poem/poem-text'
